# Generated by Django 6.0.4 on 2026-05-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liga', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jugador',
            options={'verbose_name': 'jugador', 'verbose_name_plural': 'jugadores'},
        ),
    ]
