[tool.poetry]
name = "practice02"
version = "0.1.0"
description = "Liga de E-Sports - API"
authors = ["Manuel Canga <php@manuelcanga.dev>"]
license = "GPLv2"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^6.0.4"
djangorestframework = "^3.17.1"
django-cors-headers = "^4.9.0"
djangorestframework-stubs = "^3.16.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
